### ISSUE TITLE
[not-a-issue]Translation for The Description In Jolla Store

### ISSUE THREAD

**Issue by TylerTemp** [mike7b4/mymoney#6]
Really love this app XD 

Since Jolla Store supports Chinese description according to this [answer](https://together.jolla.com/question/79317/store-app-description-translation-support/), I'd appreciate if you can put the Chinese description too :-). Hope it can help more Chinese people know this AWESOME app ;-)

Here is the Chinese translation:

* * * * * 

> MyMoney is a simple budget application for your private expense/income.

MyMoney是一个用来记录你个人收入/支出预算的简单应用。

**Comment by mike7b4** [comment]
Sorry for very late answer. 

I just added your Chinese translation to harbour lets see if it gets approved.

On Monday, February 02, 2015 00:52:00 Tyler Temp wrote:
> Really love this app XD
> 
> Since Jolla Store supports Chinese description according to this
> [answer](https://together.jolla.com/question/79317/store-app-description-tr
> anslation-support/), I'd appreciate if you can put the Chinese description
> too :-). Hope it can help more Chinese people know this AWESOME app ;-)
> 
> Here is the Chinese translation:
> 
> * * * * *
> 
> > MyMoney is a simple budget application for your private expense/income.
> 
> MyMoney是一个用来记录你个人收入/支出预算的简单应用。
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mike7b4/mymoney/issues/6

-- 
"Put mankind back on earth"
