### ISSUE TITLE
Unable to save default currency after close

### ISSUE THREAD

**Issue by TylerTemp** [mike7b4/mymoney#8]
Issue: After re-opening the app, the default currency is lost.

Re-produce:
1.  Open app, go settings -> Default currency
2.  Change it to any currency rather than British Pound, to say `Yuan`
3.  Accept
4.  Close the app
5.  Open the app
6.  The currency changed back to British Pound

Version:

Mymoney: v0.1.2

Sailfish OS: 2.0.2.48

Device: Jolla Phone 1

**Comment by mike7b4** [comment]
yes also found this when install it on Fairphone. Fix is comming hopefully this week

**Comment by mike7b4** [comment]
Fix released in harbour
